### ISSUE TITLE
Missing Transparency handle

### ISSUE THREAD

**Issue by HurricanKai** [tobimori/MC-Toolbox2#1]
Minecraft Renders Transparency as black, (my skin: EinCommandBlock) 

Also Some Error Occures, when trying to Load Transparency, which leads to an, after short rendering, not found error, !The Player is Rendererd for 2 seconds or so D:

(Testet with build From Visual Studio 2017 (Cloned with Github VS extension))

**Comment by tobimori** [comment]
Ich schreib jetzt hier mal auf Deutsch, weil ich keine Lust habe auf Englisch zu schreiben, kannst du eigentlich auch. Also du meinst, das wenn du einen transparenten Skin hast, das der weiß und nicht schwarz ist und das der nicht richtig rendern will?

**Comment by tobimori** [comment]
PS: Ich hab es gefixt, das man nur "einmal" rendern kann. (Lag an der UUID Conversion)
